/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackYourOrderRouteImport } from './routes/track-your-order'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as ReturnsRefundPolicyRouteImport } from './routes/returns-refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as OrderCancellationPolicyRouteImport } from './routes/order-cancellation-policy'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BillingTermsConditionsRouteImport } from './routes/billing-terms-conditions'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as StoreManagerDashboardRouteImport } from './routes/store-manager.dashboard'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AccountResetPasswordRouteImport } from './routes/account.reset-password'
import { Route as AccountRegisterRouteImport } from './routes/account.register'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as AccountForgotPasswordRouteImport } from './routes/account.forgot-password'
import { Route as AccountDashboardRouteImport } from './routes/account.dashboard'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackYourOrderRoute = TrackYourOrderRouteImport.update({
  id: '/track-your-order',
  path: '/track-your-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRefundPolicyRoute = ReturnsRefundPolicyRouteImport.update({
  id: '/returns-refund-policy',
  path: '/returns-refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCancellationPolicyRoute = OrderCancellationPolicyRouteImport.update({
  id: '/order-cancellation-policy',
  path: '/order-cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingTermsConditionsRoute = BillingTermsConditionsRouteImport.update({
  id: '/billing-terms-conditions',
  path: '/billing-terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreManagerDashboardRoute = StoreManagerDashboardRouteImport.update({
  id: '/store-manager/dashboard',
  path: '/store-manager/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/account/forgot-password',
  path: '/account/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDashboardRoute = AccountDashboardRouteImport.update({
  id: '/account/dashboard',
  path: '/account/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/billing-terms-conditions': typeof BillingTermsConditionsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/order-cancellation-policy': typeof OrderCancellationPolicyRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-refund-policy': typeof ReturnsRefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/track-your-order': typeof TrackYourOrderRoute
  '/wishlist': typeof WishlistRoute
  '/account/dashboard': typeof AccountDashboardRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store-manager/dashboard': typeof StoreManagerDashboardRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/billing-terms-conditions': typeof BillingTermsConditionsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/order-cancellation-policy': typeof OrderCancellationPolicyRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-refund-policy': typeof ReturnsRefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/track-your-order': typeof TrackYourOrderRoute
  '/wishlist': typeof WishlistRoute
  '/account/dashboard': typeof AccountDashboardRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store-manager/dashboard': typeof StoreManagerDashboardRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/billing-terms-conditions': typeof BillingTermsConditionsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/order-cancellation-policy': typeof OrderCancellationPolicyRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-refund-policy': typeof ReturnsRefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/track-your-order': typeof TrackYourOrderRoute
  '/wishlist': typeof WishlistRoute
  '/account/dashboard': typeof AccountDashboardRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/store-manager/dashboard': typeof StoreManagerDashboardRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/billing-terms-conditions'
    | '/cart'
    | '/checkout'
    | '/contact-us'
    | '/order-cancellation-policy'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/returns-refund-policy'
    | '/shipping-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/track-your-order'
    | '/wishlist'
    | '/account/dashboard'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/admin/dashboard'
    | '/blog/$slug'
    | '/product/$slug'
    | '/store-manager/dashboard'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/billing-terms-conditions'
    | '/cart'
    | '/checkout'
    | '/contact-us'
    | '/order-cancellation-policy'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/returns-refund-policy'
    | '/shipping-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/track-your-order'
    | '/wishlist'
    | '/account/dashboard'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/admin/dashboard'
    | '/blog/$slug'
    | '/product/$slug'
    | '/store-manager/dashboard'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/billing-terms-conditions'
    | '/cart'
    | '/checkout'
    | '/contact-us'
    | '/order-cancellation-policy'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/returns-refund-policy'
    | '/shipping-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/track-your-order'
    | '/wishlist'
    | '/account/dashboard'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/admin/dashboard'
    | '/blog/$slug'
    | '/product/$slug'
    | '/store-manager/dashboard'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BillingTermsConditionsRoute: typeof BillingTermsConditionsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactUsRoute: typeof ContactUsRoute
  OrderCancellationPolicyRoute: typeof OrderCancellationPolicyRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReturnsRefundPolicyRoute: typeof ReturnsRefundPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TrackYourOrderRoute: typeof TrackYourOrderRoute
  WishlistRoute: typeof WishlistRoute
  AccountDashboardRoute: typeof AccountDashboardRoute
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  StoreManagerDashboardRoute: typeof StoreManagerDashboardRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-your-order': {
      id: '/track-your-order'
      path: '/track-your-order'
      fullPath: '/track-your-order'
      preLoaderRoute: typeof TrackYourOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-refund-policy': {
      id: '/returns-refund-policy'
      path: '/returns-refund-policy'
      fullPath: '/returns-refund-policy'
      preLoaderRoute: typeof ReturnsRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-cancellation-policy': {
      id: '/order-cancellation-policy'
      path: '/order-cancellation-policy'
      fullPath: '/order-cancellation-policy'
      preLoaderRoute: typeof OrderCancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing-terms-conditions': {
      id: '/billing-terms-conditions'
      path: '/billing-terms-conditions'
      fullPath: '/billing-terms-conditions'
      preLoaderRoute: typeof BillingTermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-manager/dashboard': {
      id: '/store-manager/dashboard'
      path: '/store-manager/dashboard'
      fullPath: '/store-manager/dashboard'
      preLoaderRoute: typeof StoreManagerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/account/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/dashboard': {
      id: '/account/dashboard'
      path: '/account/dashboard'
      fullPath: '/account/dashboard'
      preLoaderRoute: typeof AccountDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BillingTermsConditionsRoute: BillingTermsConditionsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactUsRoute: ContactUsRoute,
  OrderCancellationPolicyRoute: OrderCancellationPolicyRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReturnsRefundPolicyRoute: ReturnsRefundPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TrackYourOrderRoute: TrackYourOrderRoute,
  WishlistRoute: WishlistRoute,
  AccountDashboardRoute: AccountDashboardRoute,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  StoreManagerDashboardRoute: StoreManagerDashboardRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
